### ISSUE TITLE
Error HCaptchaWebView not displayed 

### ISSUE THREAD

**Issue by qiusanxin** [hCaptcha/hcaptcha-android-sdk#110]
Initialize Hcaptch with different fragmentActivity, webview is abnormal when hcaptch is displayed

`
HCaptcha.getClient(fragmentActivity)?.setup(hCaptchaConfig())?.verifyWithHCaptcha()
`

The first call shows success, the second call fails

Error log

`
HCaptchaWebView not displayed because it is too large to fit into a software layer (or drawing cache), needs 10467840 bytes, only 10368000 available
HCaptchaWebView not displayed because it is too large to fit into a software layer (or drawing cache), needs 10467840 bytes, only 10368000 available
`

I tried removing 

`
HCaptchaWebViewHelper#setupWebView()
//webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null)
`

this problem can be solved

**Comment by CAMOBAP** [comment]
@qiusanxin thanks for reporting the issue.

Could you please confirm that `webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null)` removing fixes the issue for you?

Could you please share more details on the conditions when it happens (Android OS version, device model etc.)

**Comment by qiusanxin** [comment]
After I remove webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null), the problem is solved, 
Android 13 version of Mi 10Ultra

But I did not reproduce this problem on OPPO or OnePlus devices

**Comment by CAMOBAP** [comment]
@DSergiu I think we have several options here:
 - Implement some `OnWebViewConfigurer` interface which will allow the end users to configure `WebView` i.e. disable `LAYER_TYPE_SOFTWARE` and set https://developer.android.com/reference/android/view/View#LAYER_TYPE_NONE for example
 - We may add explicit flag to `HCaptchaConfig` something like `HCaptchaConfig.softwareLayerType` which will be `true` buy default
 - We may remove the line https://github.com/hCaptcha/hcaptcha-android-sdk/blob/main/sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewHelper.java#L88 at our own risk. I have tested on the recent Android OSes there are no issues, but they may be on older one because per [docs](https://developer.android.com/topic/performance/hardware-accel#layers):

> .... If a view that is hardware accelerated (for instance, if your whole application is hardware acclerated), is having rendering problems, this is an easy way to work around limitations of the hardware rendering pipeline.

There are no notes about what kind of issues may be in this article, probably something like this https://stackoverflow.com/questions/20675554/webview-rendering-issue-in-android-kitkat

In my opinion, the first approach is more flexible (we provide a similar API on iOS)

**Comment by CAMOBAP** [comment]
After some additional research:
1. There is a problem with enabling back hardware acceleration, per [documentation](https://developer.android.com/topic/performance/hardware-accel#layers)
    > .... You currently cannot enable hardware acceleration at the view level. View layers have other functions besides disabling hardware acceleration.
    So once we disabled it there is no reliable way to enable it back
2. Looks better choice at the moment
3. Removing this line may lead to unwanted UI artifacts

**Comment by CAMOBAP** [comment]
`HCaptchaConfig.disableHardwareAcceleration` now allow to configure this behavior
